name: wheel_chair
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0 # Use the latest compatible version
  tflite_flutter: ^0.11.0 #de elyy sh8ala eltnyaa la 7/5/2025
  permission_handler: ^11.4.0  # For managing permissions
  flutter_tts: ^4.2.2  # Optional:For text-to-speech feedback
  record: ^6.0.0 # Make sure this is the latest version
  flutter_sound: ^9.25.4
  speech_to_text: ^7.0.0






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.13

 

flutter:
    uses-material-design: true

    assets:
    - assets/wheelchair.png
    - assets/converted_model.tflite



  

